### ISSUE TITLE
 After upgrading to 36 from 35, Getting issue- 1:1  ✖  Unknown rule lightness-notation, in all scss file.

### ISSUE THREAD

**Issue by ankitakratech** [stylelint-scss/stylelint-config-standard-scss#148] opened 2023-12-29 12:31 UTC
After runing "npx stylelint --custom-formatter ./setup/stylelint-multi-formatter.js --color "src/**/*.scss"" in terminal i getting below error
" 1:1  ✖  Unknown rule lightness-notation  lightness-notation" in all my scss file.
I'm using **"stylelint": "^15.10.2",** and "stylelint-config-standard": "^36.0.0",
<img width="836" alt="Screenshot 2023-12-29 at 6 00 19 PM" src="https://github.com/stylelint-scss/stylelint-config-standard-scss/assets/53000973/9270991c-97fb-4cb6-b811-6acb8d0a05e1">

**Comment by olemen-WittGruppe** [comment] 2024-01-02 15:56
same issue, I'm using "stylelint:15.11.0", stylelint-config-standard:36.0.0

**Comment by kristerkari** [comment] 2024-01-04 02:24
Thanks for reporting @ankitakratech !

Can you please try with the new version:
https://github.com/stylelint-scss/stylelint-config-standard-scss/releases/tag/v13.0.0

**Comment by callumacrae** [comment] 2024-01-04 11:09
I had the same issue and it's because I needed to update `stylelint` :)

**Comment by hundehausen** [comment] 2024-01-04 13:46
@kristerkari I still have this issue with stylelint-config-standard-scss  in version 13

**Comment by kristerkari** [comment] 2024-01-04 22:02
Looks like the problem is resolved now :) Closing.

**Closed by kristerkari** 2024-01-04 22:02 UTC
